<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>[[put title here]] by Icons8</title>
<style type="text/css">

	body {
		margin: 0 auto;
		width: 2015px;
		min-width: 350px;
		color: #68696A;
		background-color: #ffffff;
		background-size: 100%;
		background-position: 100% 100%;
	}
	h1, h2, h3 {
		font-family: Sanchez,serif;
		font-weight: 400;
		font-style: normal;
		margin: 3rem 1rem 0;
		color: #EF6C00;
	}
	a {
		font-family: Sanchez,serif;
		font-weight: 400;
		font-style: normal;
		color: #EF6C00;
	}
	a:hover {
		color: #000;
	}
	.icon {
		width: 48px;
		height: 48px;
	}
	.office_icon_block {
		display: inline-block;
		width: 80px;
		margin: 15px 25px 0 25px;
	}
	.one-icon {
		width: 80px;
		text-align: center;
		margin: 25px 0 0 0;
	}
	img.icon.icon_16 {
		width: 16px;
		height: 16px;
	}
	img.icon.icon_30 {
		width: 30px;
		height: 30px;
	}
	.icon.icon_80 {
		width: 80px;
		height: 80px;
	}
	.icon.icon_40 {
		width: 40px;
		height: 40px;
	}
	img {
		color: #fff;
	}
	.container {
		position: relative;
		z-index: 1;
	}
</style>
</head>
<body>

<div class="container">

	<p>
		<?php
		/** @var \SplFileInfo $file */
		foreach ($files as $name => $sizeFiles)
		{ ?>

	<div class="office_icon_block">
		<?php
		foreach ($sizeFiles as $size => $file) {
			$path = rawurldecode($file);
			$title = preg_replace('/()\.svg$/u', '$1', $file->getBasename());
			echo <<<HTML
<div class="one-icon"><img class="icon icon_{$size}" src="{$path}" title="{$title}" /></div>\n
HTML;
		} ?>
	</div>
	<?php
	} ?>
	</p>

	<p>
		<a href="http://icons8.com/">icons8.com</a>
		<br/>
		<br/>
		<a href="https://twitter.com/icons_8">Twitter</a>
		&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="https://www.facebook.com/Icons8?ref=hl">Facebook</a>
		&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="https://plus.google.com/+Icons8">Google+</a>
	</p>
</div>

<link href="http://fonts.googleapis.com/css?family=Sanchez" rel="stylesheet" type="text/css">
</body>
</html>