<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>[[put title here]] by Icons8</title>
<style type="text/css">
*, :after, :before {
	box-sizing: border-box;
}
body {
	margin: 0 auto;
	max-width: 880px;
	min-width: 350px;
	color: #68696A;
	background-color: #ffffff;
	background-size: 100%;
	background-position: 100% 100%;
}
h1, h2, h3 {
	font-family: Sanchez,serif;
	font-weight: 400;
	font-style: normal;
	margin: 3rem 1rem 0;
	color: #EF6C00;
}
a {
	font-family: Sanchez,serif;
	font-weight: 400;
	font-style: normal;
	color: #EF6C00;
}
a:hover {
	color: #000;
}
.icons-set_element {
	display: inline-block;
	-webkit-transition: 75ms linear all;
	transition: 75ms linear all;
}
.icons-set__icon {
	margin: 0 .6rem .6rem 0;
	color: #9b9b9b;
	width: 6rem;
	height: 6rem;
	position: relative;
	overflow: hidden;
	display: inline-block;
	text-decoration: none;
	cursor: pointer;
	text-align: center;
	padding: 0 0 .3rem;
	border: 2px solid transparent;
	border-radius: 6px;
	-webkit-transition: 75ms linear all;
	transition: 75ms linear all;
}
.icons-set__icon:hover {
	background: #f4f4f4;
}
.icons-set__icon-svg {
	display: inline-block;
	width: 50px;
	height: 50px;
	min-height: 3rem;
	margin: .5rem 0 0;
}
.icons-set__icon-data {
	position: relative;
	height: 2rem;
}
.icons-set__icon-title {
	visibility: visible;
	opacity: 1;
	max-height: 28px;
	line-height: 14px;
	position: absolute;
	top: 50%;
	left: 0;
	right: 0;
	font-size: 12px;
	-webkit-transform: translateY(-50%);
	-ms-transform: translateY(-50%);
	transform: translateY(-50%);
	-webkit-transition: all .3s ease-in-out;
	transition: all .3s ease-in-out;
}
img {
	color: #fff;
}
.container {
	position: relative;
	z-index: 1;
}
</style>
</head>
<body>

<div class="container">
	<h2>[[put title here]] by <a href="http://icons8.com/">Icons8</a></h2>

	<p class="icons-set">

	<?php
		/** @var \SplFileInfo $file */
		foreach($files as $file)
		{
			$path = rawurldecode($file);
			$title = preg_replace('/()\.svg$/u', '$1', $file->getBasename());

			echo <<<HTML
				<div class="icons-set_element">
						<div class="icons-set__icon">
							<div class="icons-set__icon-svg">
								<img class="icon" src="{$path}" title="{$title}"/>
							</div>
							<div class="icons-set__icon-data">
								<div class="icons-set__icon-title">{$title}</div>
							</div>
						</div>
					</div>
HTML;
		} ?>
	</p>

	<p>
		<a href="http://icons8.com/">icons8.com/</a>
		<br/>
		<br/>
		<a href="https://twitter.com/icons_8">Twitter</a>
		&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="https://www.facebook.com/Icons8?ref=hl">Facebook</a>
		&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="https://plus.google.com/+Icons8">Google+</a>
	</p>
</div>

<link href="http://fonts.googleapis.com/css?family=Sanchez" rel="stylesheet" type="text/css">
</body>
</html>